### PR TITLE
build-configs.yaml: add Linus Walleij's gpio tree

### PR DESCRIPTION
**Pull request by roxell**
Add Linus Walleij's gpio tree and three branches 'devel', 'fixes' and
'for-next'.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Comment by gctucker** [comment]
Ideally these branches should be checked every 24h as discussed on this thread:
https://groups.io/g/kernelci/message/260

However, all the branches currently monitored are checked every hour.  We may add a feature to fine-tune that on a per-branch basis, but in the meantime would it be possible to have a GPIO branch that only gets updated at most once every day?

**Comment by roxell** [comment]
If I understand the thread and LinusW's reply he is fine with updating his branches once a day.

https://groups.io/g/kernelci/message/288

**Comment by gctucker** [comment]
Yes, that's great.  So we can enable these branches now, and when we have configurable update frequencies support in KernelCI then we can set it to "daily" it won't matter how often the branches are updated during one day.

**Comment by mattface** [comment]
Sounds like we're all in agreement here so I'll merge this

**Comment by gctucker** [comment]
@mattface Please see my last comment - this won't work.  There needs to be a separate entry for each branch.

**Comment by gctucker** [comment]
Ah sorry it was stuck as part of a review so it didn't appear.

**Comment by mattface** [comment]
Ah yes, @roxell can you fix this as requested in a new PR

**Comment by roxell** [comment]
just created one https://github.com/kernelci/kernelci-core-staging/pull/103

**Pull request merged**
