### PR TITLE
dockerfiles: include GCC plugin dev packages for ARM, AArch64 and x86

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
Install the appropriate gcc-plugin-dev .deb package along with each
toolchain that targets an architecture that has GCC plugin support
in Linux.

Signed-off-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
> Please add the new packages on a separate line and keep them in alphabetical order. That helps a lot reading diffs, reducing diff noise and avoiding mistakes in the long run.
> 

OK

> Then it seems like we need to change something in the build jobs to actually build the GCC plugin modules. Reading the doc, this can either be done with `make gcc-plugins` or by enabling `CONFIG_GCC_PLUGIN_CYC_COMPLEXITY` in the kernel config. If we don't do this, then it's hard to justify adding these extra packages to the Docker images as they won't be used in production.

This is incorrect. A normal kernel build will first build the host plugins that the particular Kconfig depends on. The cyclic complexity plugin is just an example that should never be enabled in real-world configurations.

For example, this plugin

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=189af4657186da08a2e79fb8e906cfd82b2ccddc

is enabled by default for any config that enables CONFIG_STACK_PROTECTOR and CONFIG_GCC_PLUGINS, and will be used in a normal kernel build/boot in that case.

**Comment by gctucker** [comment]
> > Then it seems like we need to change something in the build jobs to actually build the GCC plugin modules. Reading the doc, this can either be done with `make gcc-plugins` or by enabling `CONFIG_GCC_PLUGIN_CYC_COMPLEXITY` in the kernel config. If we don't do this, then it's hard to justify adding these extra packages to the Docker images as they won't be used in production.
> 
> This is incorrect. A normal kernel build will first build the host plugins that the particular Kconfig depends on. The cyclic complexity plugin is just an example that should never be enabled in real-world configurations.
> 
> For example, this plugin
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=189af4657186da08a2e79fb8e906cfd82b2ccddc
> 
> is enabled by default for any config that enables CONFIG_STACK_PROTECTOR and CONFIG_GCC_PLUGINS, and will be used in a normal kernel build/boot in that case.

OK, thanks for the clarification.  However it seems like there aren't any upstream defconfigs with the configs you mentioned enabled, presumably because they don't make sense in production kernel builds.  I see there's a commit in your `for-kernelci` branch that does just that:

https://git.kernel.org/pub/scm/linux/kernel/git/ardb/linux.git/commit/?h=for-kernelci&id=0c1304a5679d3969406a23e238785989990fc8ca

I guess the plugin modules would only be built on this branch, or if any other branch has similar patches to enable these configs.  Is this correct?

We're currently discussing how to manage test configurations and config fragments in KernelCI (cc @danrue).  I guess it would seem useful to have the ability to enable these GCC plugin configs on arbitrary branches so you wouldn't need to keep carrying a patch, and we could enable it say, on linux-next etc...  See what we've done with the virtual video drivers for example (link below).  How does that sound?

https://github.com/kernelci/kernelci-core/blob/master/jenkins/kernel-trigger-tarball.sh#L159

**Comment by gctucker** [comment]
OK thanks, sounds great.  Next step is to give that a spin on staging.kernelci.org, I'll put a comment here with the results.

**Comment by gctucker** [comment]
Tested OK with gcc-7 on arm, arm64 and x86_64.  Here are the full build logs:
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/arm/multi_v7_defconfig/build.log
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/arm64/defconfig/build.log
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/x86_64/defconfig/build.log

The `HOSTCXX -fPIC scripts/gcc-plugins/`*.o lines show that the plugins are being built.

I'll give it another go with gcc-8 for completeness then this should be ready to merge.  There's also some boot tests running with these builds, we'll see if they all work as expected.

**Comment by gctucker** [comment]
Tested OK on GCC v8.2.0 as well (now showing the compiler version at the top of the logs):
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/arm/multi_v7_defconfig/build-gcc-8.log
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/arm64/defconfig/build-gcc-8.log
http://staging-storage.kernelci.org/gtucker/kernelci-local/kernelci-local-snapshot-016-8-g1ad704564490/x86_64/defconfig/build-gcc-8.log

**Pull request merged**
