### PR TITLE
add build and trigger support for ARCH=arc

### PR DESCRIPTION
**Pull request by khilman**

### CODE REVIEW

**Comment by khilman** [comment]
This is for review only.  I can rebase on the  dockerfile restructuring from @gctucker when that is merged.

**Comment by gctucker** [comment]
@khilman ooi is there any hardware in any KernelCI lab featuring an `arc` CPU?

**Comment by khilman** [comment]
@gctucker yes, we have an HSDK board in the BayLibre lab that's waiting to be added.

**Comment by khilman** [comment]
rootfs (for buildoot) already ready: http://storage.kernelci.org/images/rootfs/buildroot/kci-2018.05/arc/

Unfortunately, debian support is not ready.

**Comment by gctucker** [comment]
Great.  I guess we can merge this now and start producing builds, then later on add the device type and rootfs in the test configs to start boot tests.

**Comment by gctucker** [comment]
Oh sorry realised this was waiting for the Dockerfile stuff to be merged...

**Comment by gctucker** [comment]
Reverted - @mattface are you happy with #25 now?

**Pull request merged**
