### PR TITLE
T10722 split x86 arch

### PR DESCRIPTION
**Pull request by gctucker**
Split the `x86` arch into `i386` and `x86_64`.  This is primarily to be able to run 64-bit userspace as otherwise only the 32-bit ones are used with all x86 kernels.  The current Buildroot file systems are only 32-bit, so this directly applies only to the Debian ones.

### CODE REVIEW

**Comment by ana** [comment]
LGTM. I have a question on the update of `test-configs.yaml` to consolidate Debian rootfs  definitions.
How it will work when we want to use http://staging-storage.kci.o URLs? It's possible to change the line 16 to point to staging for testing locally but then, when we merge stuff in production, we'll have broken URLs in the YAML.

**Comment by gctucker** [comment]
To build with rootfs image from staging-storage.kernelci.org, we can have an extra patch on some branches and use them in sub-folder on staging.  I've made a patch like this on my branch, used in `gtucker/lava-boot-v2`:
https://github.com/gctucker/kernelci-core-staging/commit/d8f2ebf1c74d3518cd016d942f2cb04e3abddbad

**Comment by ana** [comment]
> To test with rootfs images from staging-storage.kernelci.org, we can have an extra patch on some branches and use them in sub-folder on staging. I've made a patch like this on my branch, used in `gtucker/lava-boot-v2`:
> [gctucker@d8f2ebf](https://github.com/gctucker/kernelci-core-staging/commit/d8f2ebf1c74d3518cd016d942f2cb04e3abddbad)

Yes, that's what I meant on my comment with updating the line 16.  Let me re-ask with an example, I want to add the rootfs images for `stretch-foo` and I work on then in staging, I'd add to `test-confis.yaml`:

```
  debian_stretch-foo_ramdisk:
    type: debian
    ramdisk: 'stretch-foo/20181126.0/{arch}/rootfs.cpio.gz'
```
With my modified `test-confis.yaml`,  this will download the tarball from  `http://staging-storage.kernelci.org/images/rootfs/debian/stretch-foo/20181126.0/{arch}/rootfs.cpio.gz`

After merging my changes,  `test-confis.yaml`  will be pointing to  `http://storage.kernelci.org/images/rootfs/debian/stretch-foo/20181126.0/{arch}/rootfs.cpio.gz`
that doesn't exist.

IMHO the current situation with have with the yaml file pointing to rootfs in staging is better than a situation where they would point to URLs with the rootfs that don't exist.

**Comment by gctucker** [comment]
What I've been doing for the last PRs to sync up staging with production was to run all the rootfs jobs after merging into kernelci-core master and update the URLs in the YAML with the latest builds, then use that to run a test job before enabling all the trees again.

What we can do now is set a generic URL in the YAML and use symlinks on the server to point to the latest rootfs versions.  Then after updating the production branch, the symlink would need to be updated rather than the YAML.  We can probably update the `upload` API to create that symlink automatically in the backend automatically.

**Comment by ana** [comment]
> What I've been doing for the last PRs to sync up staging with production was to run all the rootfs jobs after merging into kernelci-core master and update the URLs in the YAML with the latest builds, then use that to run a test job before enabling all the trees again.

I've seen that. I still like more the current situation. When doing local testing,  I often want to download some rootfs from my local storage and others from staging-storage.kci.o and/or storage.kci.o
Do you think it would be possible to  add an override to your current implementation? I mean something like checking storage.kci.o by deault unless the yaml file has instead of  `type: debian`, has a `url` field and the script will use that url instead of the one in `file_system_types`.

> What we can do now is set a generic URL in the YAML and use symlinks on the server to point to the latest rootfs versions. Then after updating the production branch, the symlink would need to be updated rather than the YAML. We can probably update the `upload` API to create that symlink automatically in the backend automatically.

Yes, we should look at this now we have several images and updating the url is becoming burdensome.

**Comment by gctucker** [comment]
> When doing local testing, I often want to download some rootfs from my local storage and others from staging-storage.kci.o and/or storage.kci.o
> Do you think it would be possible to add an override to your current implementation?
That seems to only be useful during development, so I'm not too keen to add complexity to the code.  How about adding your local file system types and doing this all in the YAML instead?  Something like this:
```
file_system_types:

debian_local:
    url: 'http://localhost/somewhere'
    arch_map:
      armhf: [{arch: arm}]
      amd64: [{arch: x86_64}]

file_systems:

  debian_stretch_ramdisk:
    type: debian_local
    ramdisk: 'stretch/latest/{arch}/rootfs.cpio.gz'
```

**Comment by ana** [comment]
> That seems to only be useful during development, so I'm not too keen to add complexity to the code. How about adding your local file system types and doing this all in the YAML instead? Something like this:
> 
> ```
> file_system_types:
> 
> debian_local:
>     url: 'http://localhost/somewhere'
>     arch_map:
>       armhf: [{arch: arm}]
>       amd64: [{arch: x86_64}]
> 
> file_systems:
> 
>   debian_stretch_ramdisk:
>     type: debian_local
>     ramdisk: 'stretch/latest/{arch}/rootfs.cpio.gz'
> ```

Thanks, this should work. 
I still don't see the interesst of the change to consolidate Debian rootfs definitions but I don't want to block this either.

**Comment by gctucker** [comment]
The point is to avoid having to repeat identical definitions for all the Debian file systems, such as the arch map and base url, when the `file_system_types` definitions are there exactly for this purpose of defining a family of file systems.

**Comment by gctucker** [comment]
OK maybe we can do something in a follow-up to make it easier when hacking around with temporary file systems, but merging this as-is for now.

**Pull request merged**
