### PR TITLE
Add RISC-V support for docker builders

### PR DESCRIPTION
**Pull request by khilman**

### CODE REVIEW

**Comment by khilman** [comment]
@gctucker I addressed your changelog wording comments, and rebased it onto staging/master, so I think it's ready for a round of testing in staging.

**Comment by gctucker** [comment]
Thanks @khilman, will give it a spin.

Note: One thing worth mentioning here is that `riscv64` not an architecture name known to the kernel build system (as discussed on IRC).  It's the first one of this kind, for x86 it's possible to use i386 or x86_64 but there's no such equivalent for RISC-V.  What it means is that we need to keep translating `riscv*` as `riscv` for the kernel builds.  It might be an issue with paths on the storage server, and in other places too.  Testing will help prove this in practice; worst case we'll have to either have a nasty hack just for RISC-V in the short term or just fix this properly with some real build configuration like we did with `test-configs.yaml`.

**Comment by gctucker** [comment]
Gave it a try and found a few issues with arch names.  Essentially, the convention in all KernelCI code is actually to use the kernel names i.e. `riscv` in this case, and have a mapping for toolchain and user-space arch naming conventions.  We have to stick to this otherwise we'll have too many issues, so the arch to add to the list has to be `riscv`.  Right now, we only care about 64-bit, so the translation is pretty simple.  When we start adding other RISC-V variants then we'll need a more advanced configuration solution - or maybe earlier than that to clean up `build-trigger.jpl`.

So I'll tweak the code a bit as atm it's failing to find a docker image with `riscv` since they're tagged `riscv64`...  Stay tuned.

**Comment by gctucker** [comment]
@khilman With the 2 extra patches, I finally got a riscv defconfig build:
https://staging.kernelci.org/build/id/5beaa77fcf3a0f0709fe1ff2/
https://staging-ci.kernelci.org/job/gtucker/job/kernel-build/246/console

Please squash the FIXUP commit with "add riscv to ARCH_LIST" if you agree as this is imo the best way around in the end...  I've also rebased this PR.

I can give it a final spin when the commits are all cleaned up.

**Comment by khilman** [comment]
OK, rebased and squashed the last 2 commits.

I'll also need a follow-up change to build.py to copy the 'vmlinux' image for riscv builds, since that's currently the only kernel image generated.

**Comment by mattface** [comment]
@khilman how big are these vmlinux images? Aren't they usually huge? We might have a storage space issue if so.

**Comment by khilman** [comment]
Closing in favor of #49

**Pull request closed without merging**
