### PR TITLE
test-configs.yaml: add meson-gxl-s805x-p241

### PR DESCRIPTION
**Pull request by montjoie**
This patch add meson-gxl-s805x-p241 device-type

### CODE REVIEW

**Comment by khilman** [comment]
@montjoie Is the LAVA device-type submitted upstream for this platform?

**Comment by montjoie** [comment]
Yes it is upstream since the 4 Dec 2018

**Comment by gctucker** [comment]
Tested OK on staging: https://staging.kernelci.org/boot/id/5c508073cf3a0fc1aeead44f/

**Comment by gctucker** [comment]
Interestingly it failed to boot with the gcc-8 kernel: https://staging.kernelci.org/boot/id/5c50822acf3a0fc253ead42b/

**Comment by gctucker** [comment]
Ah that was just a `BOOTP` timeout (makes more sense than gcc-8...).

**Pull request merged**
