### PR TITLE
jenkins/dockerfiles: add clang-8 support

### PR DESCRIPTION
**Pull request by khilman**
Use the pre-built debian packages from apt.llvm.org for installing a
recent clang compiler that can build upstream kernels.

Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by khilman** [comment]
I've manually verified that this version of clang can build upstream for arm and arm64.

**Comment by gctucker** [comment]
While it's good to have an image to build kernels, I don't think we can use it in KernelCI yet as we don't have a way to build the same kernels multiple times with different compilers.

**Comment by mattface** [comment]
I'm going to merge this because it will be useful for me to have alternatives to GCC in the very near future

**Comment by gctucker** [comment]
Has it actually been tested by building a kernel on Jenkins with Clang?

**Pull request merged**
