### PR TITLE
T12386 build configs in YAML and trigger job in Pipeline

### PR DESCRIPTION
**Pull request by gctucker**
This is a first implementation using `build-configs.yaml` with a command line interface `kci_build` to decouple the logic from Jenkins, as well as a Pipeline replacement for `kernel-trigger-tarball`.

Things that still need to be done:
* add special config fragments (kselftest, virtualvideo)
* decide whether running another sub-job to produce each tarball rather than just a parallel step which makes logs hard to read
* populate full `build-configs.yaml` file and test it
* add docstrings

### CODE REVIEW

**Comment by gctucker** [comment]
I've started to test this on staging with this job:
https://staging-ci.kernelci.org/job/gtucker/job/kernel-tree-monitor/

**Comment by khilman** [comment]
Look like a step in the right direction.

Related feature request for build-configs.yaml: how to specify compilers, and specifically how to specify compilers that can only build a subset of arches or trees.  (e.g. clang can only build on arm64 and on mainline and linux-next)

**Comment by gctucker** [comment]
@khilman I'll add that in a follow-up PR since this one is alread 14 patches long.  Basically the idea is to add a `build_environment` attribute to each build configuration, with a default one to avoid having to repeat "gcc-7" everywhere.  Then you could have something like this:
```
  next:
    tree: next
    branch: 'master'

  next_clang:
    tree: next
    branch: 'master'
    arch_list: ['arm64', 'x86_64']
    build_environment: 'clang-8'
```
That way, the "regular" next/master branch will be built on all the available architectures with the standard compiler, and the `next_clang` configuration is to define a combination of the next/master branch with a subset of architectures and an alternative compiler i.e. `clang-8` in this example.

**Comment by gctucker** [comment]
@mattface No, as I said in a previous commit, this PR is big enough like that and can be merged to replace the current tarball trigger and tree-branch config.  Follow-up PRs will cover multiple compilers (build env) and email recipients.

**Comment by gctucker** [comment]
Tested OK on staging, here are the builds and boots:
https://staging.kernelci.org/build/gtucker/branch/kernelci-local/kernel/kernelci-local-snapshot-026-6-g43460b6028fc/
https://staging.kernelci.org/boot/all/job/gtucker/branch/kernelci-local/kernel/kernelci-local-snapshot-026-6-g43460b6028fc/
I've also let it create tarballs for all the monitored branches, artificially aborting before doing the actual builds:
http://staging-storage.kernelci.org/?C=M&O=D
and a subset of a few trees built as well such as next:
https://staging.kernelci.org/build/next/branch/master/kernel/next-20190206/
Building a whole tree with ~200 builds is not practical on staging, hence the subset to prove the logic works.
I've also confirmed that the kselftest fragment is correctly added to the source tarball, as well as the virtualvideo fragment for media and gtucker trees.

**Pull request merged**
