### PR TITLE
Ssuite testrootfs

### PR DESCRIPTION
**Pull request by roxell**
This suite evaluates:
- responsiveness, by measuring start-up times of real applications
  under real background workloads
- latency for soft real-time applications, by measuring playback
  quality (drop rate) of video and audio under real background
  workloads
- speed of code-development tasks (make, git checkout, git merge, git
  grep) under real background workloads, plus responsiveness while one
  of these dev tasks is executed
- minimum per-client bandwidth guaranteed to a set of clients doing
  any possible type of I/O
- maximum per-client latency guaranteed to a set of clients doing any
  possible type of I/O
- throughput with processes doing filesystem or raw I/O in parallel
  (figure of merit measured by many other suites too)
- throughput with processes doing interleaved I/O, which mimics the
  typical I/O pattern of applications like qemu

### CODE REVIEW

**Comment by roxell** [comment]
I updated the pull req with the information from the readme.
Hope that was what you meant.

**Comment by gctucker** [comment]
It would probably deserve a page on the wiki (like any test suite really...) once it's merged.

Github link fwiw: https://github.com/Algodev-github/S

What's important from a KernelCI point of view is to define the areas of the kernel being tested here.  Maybe the test plan should actually be called "I/O performance" or something like that, or does it really need to be just about running the "S" test suite?

**Comment by roxell** [comment]
I like that idea to use the name 'I/O performance', so I'll rename where I've added the name 'ssuite' with 'IO_performance' then we can add other 'I/O performance' test suites to this rootfs.

**Comment by ana** [comment]
Hey @roxell:
In top of the rename to I/O performance, a few comments/requests:
- could you please add in the commit messages what is this test about?
- you're copying everything under /opt/ and it's about 25M, with the WALL-E trailer being 24M of them. According to https://github.com/Algodev-github/S/blob/master/USAGE-INSTALLATION#L95   your test plan won't run the video test so maybe we can leave the trailer out for now 
- in `stretchssuite.jpl` you're installing packages that should be already in the rootfs (e.g. bash or coreutils), and also libaio-dev should pull libaio1, so not need to add this last one. Could you check the dependencies really needed there?
- Do you have a link to a lava log somewhere with a run of this test plan?

thanks =)

**Comment by gctucker** [comment]
@roxell Could you please resubmit this PR in https://github.com/kernelci/kernelci-core as we're shutting down this `kernelci-core-staging` repo this week?

**Comment by gctucker** [comment]
@roxell Please resubmit this PR in https://github.com/kernelci/kernelci-core if you still want to have it added to KernelCI.

**Pull request closed without merging**
