### PR TITLE
build.py: updates for MIPS

### PR DESCRIPTION
**Pull request by khilman**
Now that I have a MIPS board in my lab that's actually booting mainline, I was able to test everything and found a couple minor bugs for getting the MIPS kernels properly build and installed/published.

### CODE REVIEW

**Comment by khilman** [comment]
Tested on staging: https://staging-ci.kernelci.org/job/khilman/job/kernel-build/28/console

**Comment by gctucker** [comment]
This does seem to work with gcc-7 but it doesn't work with the special gcc-6.3.0 images, they fail with this error:
```
Traceback (most recent call last):
  File "/home/buildslave/workspace/workspace/kernel-build@6/kernelci-core/build.py", line 247, in <module>
    cc_version = subprocess.check_output(cc_cmd, shell=True).splitlines()[0]
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'mips-linux-gnu-gcc --version 2>&1' returned non-zero exit status 127
```
@mattface @khilman Can we just switch to the regular gcc-7 images now thanks to this patch?

To avoid regression in production, I'll revert this now and keep using 6.3.0 until we've sorted out this issue.

**Comment by gctucker** [comment]
@khilman OK thanks for confirming this.  Also please see the meeting minutes from this Monday's weekly call, there was some concerns about the gcc-7 Debian toolchain packages for MIPS that would not be able to build all the architecture variants.

Note: Using the regular gcc-7 toolchain also means getting rid of a couple of hacks in the build job generation that were forcing the 6.3.0 toolchain to be used with MIPS.

**Comment by gctucker** [comment]
Great, so we should also remove the hack to force 6.3.0 with MIPS and remove the corresponding Dockerfile for 6.3.0.
cc @mattface

**Pull request merged**
